### ISSUE TITLE
ycm补全python第三方库好慢

### ISSUE THREAD

**Issue by starifly** [TTWShell/legolas-vim#100]
比如import numpy as np
a = np.
这样要过2秒才能弹出窗口，当然补全import这些很快

**Comment by TTWShell** [comment]
抱歉，这个是ycm的原因，建议去ycm那边去提issue哎。

**Comment by starifly** [comment]
请教下有没有其它补全Python第三方库快的插件

**Comment by TTWShell** [comment]
倒是没有注意，建议你调研一番，也期待给个反馈😊

**Comment by starifly** [comment]
好的
