### ISSUE TITLE
E319: Sorry, the command is not available in this version: py3 << EOF

### ISSUE THREAD

**Issue by luowenyue** [TTWShell/legolas-vim#108]
新装的Mac os 10.13系统 自带python是2.7版本的

安装完您的配置后 vim打开文件提示：
Error detected while processing /Users/voodoo/.vimrc:
line  164:
E319: Sorry, the command is not available in this version: py3 << EOF
line  165:
E492: Not an editor command: import os
line  166:
E492: Not an editor command: import sys
line  167:
E15: Invalid expression: 'VIRTUAL_ENV' in os.environ:
line  276:
E171: Missing :endif
Press ENTER or type command to continue

请问是缺少什么没安装么 pyenv已经通过brew安装

**Comment by TTWShell** [comment]
你好，安装一下py3应该可以解决这个问题。

**Comment by luowenyue** [comment]
感谢，安装python3后解决了这个问题
