### ISSUE TITLE
无法在Deepin安装

### ISSUE THREAD

**Issue by buppter** [TTWShell/legolas-vim#109]
想在deepin使用，但是提示不支持此系统

**Comment by TTWShell** [comment]
感谢你的反馈。

建议看下安装脚本。
逻辑是：1. 识别系统；2. 运行该系统的依赖安装脚本；3. 安装插件。
第2步可能不同，需要复用或者单独写。第1/3步一般不需要更改。

欢迎测试后提pr。

**Comment by buppter** [comment]
非常感谢。

修改了安装脚本，将Deepin添加到了识别的系统中。
已经成功安装了
![微信截图_20190413131301](https://user-images.githubusercontent.com/43202996/56074993-ee68f900-5ded-11e9-871a-0e4d96bd1937.png)

**Comment by TTWShell** [comment]
客气了，大家一起维护🙏
