### ISSUE TITLE
vim8建议更换安装方式

### ISSUE THREAD

**Issue by pokitpeng** [TTWShell/legolas-vim#111]
vim8编译安装太慢了，建议更换安装方式，比如

`yum remove vim-* -y \
&& wget -P /etc/yum.repos.d/  https://copr.fedorainfracloud.org/coprs/lbiaggi/vim80-ligatures/repo/epel-7/lbiaggi-vim80-ligatures-epel-7.repo \
&& yum  install vim-enhanced sudo -y`

**Comment by TTWShell** [comment]
如果都是centos7，这样做是可以的。
采用编译安装的做法就是**保证系统升级、更换不需要修改相关代码**。能自动解决系统兼容的采用yum brew等命令安装，不能的采用编译安装方式。
如果确定仅使用centos7，建议fork然后修改匹配自身系统。

**Comment by biganxin** [comment]
Welcome the best developers to the PlatON ecosystem
https://github.com/LatticeX-Foundation/dev-bounties/blob/main/Developer%20Bounty%20Program(Phase-I).md
