### ISSUE TITLE
怎么删掉你给的插件

### ISSUE THREAD

**Issue by wangxiang1099** [TTWShell/legolas-vim#47]
每次安装都报错，想删也不会删 弄的我连最初VIM都用不了了

**Comment by TTWShell** [comment]
哪个插件报错？具体报什么错？如果不是ycm，直接在vimrc里面的插件栏删掉即可。另外，插件都是托管在github，没有翻墙，安装起来是很痛苦。

**Comment by TTWShell** [comment]
另外，安装之前都是有备份的。在 ~/.vim.2017xxxx 文件夹里面。vimrc 在.vimrc.2017xxxx

**Comment by TTWShell** [comment]
感谢提醒，修复并增强了备份
