### ISSUE TITLE
怎样显示函数列表

### ISSUE THREAD

**Issue by hanwei2008** [TTWShell/legolas-vim#65]
你好，请问怎样显示示例中 右侧的函数列表。另外，有没有一个比较全一点的教程啊

**Comment by TTWShell** [comment]
@hanwei2008 你好，这个feature被去掉了。函数列表那个是用ctags插件，但是，实际使用中，发现大项目会非常影响性能，用都没法用。然后最重要的函数跳转，ycm已经做的很好了，相对而言，ctags就比较鸡肋了。

全的教程是没有的，文档只是列出了比较常用的东西。有些插件的使用，还需要自己看看文档。如果你觉得需要补充的或者有更好的插件，欢迎提pull request。

**Comment by hanwei2008** [comment]
算是入门了，谢谢哈。有时间也折腾一下

**Comment by TTWShell** [comment]
@hanwei2008 客气，有好东西记得推荐给我😄
