### ISSUE TITLE
Undefined variable: g:ale_emit_conflict_warnings

### ISSUE THREAD

**Issue by levylll** [TTWShell/legolas-vim#66]
尴尬了，装了一下报了这个错。。。。
具体报错内容如下
```
Error detected while processing /Users/levy/.vim/bundle/ale/after/plugin/ale.vim:
line    7:
E121: Undefined variable: g:ale_emit_conflict_warnings
E15: Invalid expression: !g:ale_emit_conflict_warnings
Press ENTER or type command to continue
```
不造发生了什么，请求指点一下~多谢了~

对了，进入之后YCM也有问题，YCM的问题跟装k-vim一样。。。。

```
YouCompleteMe unavailable: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecode
r
  Referenced from: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```
我在网上查了几个解决方案，没有解决掉。。。请求指点一下，多谢了~

**Comment by TTWShell** [comment]
ale 应该是新版的有bug。可以checkout到 5172934 。 ycm的问题，你装了py2了吗？
os版本多少？

**Comment by levylll** [comment]
@TTWShell 会不会是我vim的版本不对应呢，我这边vim是8.0
5172934是指什么commit么？似乎没这个commit版本啊。。。
python 有装啊
os版本
macos sierra
10.12

**Comment by TTWShell** [comment]
@levylll 昨晚ale更新了代码。我刚update了，没有问题。ycm那个问题没遇到过哎，不知道你的环境是怎么样的。

**Comment by TTWShell** [comment]
@levylll 可以执行下vim --version看下

**Comment by levylll** [comment]
YCM的那个问题解决了。。。。确实是python版本的问题，我使用了 brew uninstall python把brew装的2.7.13版本给卸载了，然后就没问题了。。。。我再整个重新搞一下。。。。

**Comment by levylll** [comment]
现在基本上是OK了，但是下面的条条那块，insert 后面的分支的那个小图标，我这里都是问号。。。请问怎么调整呢~？
@TTWShell

**Comment by TTWShell** [comment]
@levylll  https://github.com/TTWShell/legolas-vim/#问题集锦 这个看下文档

**Comment by levylll** [comment]
T老师，我重装了下，ale似乎还是不行
还是那个错误
```
Error detected while processing /Users/levy/.vim/bundle/ale/after/plugin/ale.vim:
line    7:
E121: Undefined variable: g:ale_emit_conflict_warnings
E15: Invalid expression: !g:ale_emit_conflict_warnings
```

**Comment by TTWShell** [comment]
@levylll  1小时之前测试，没有问题，不知道你这个什么情况😭

**Comment by levylll** [comment]
```
if !g:ale_emit_conflict_warnings
    finish
endif
```
我看报错的就是这么句话
这句话的作用是什么？
要不我直接把这句去掉呢？~
@TTWShell 
别的都没什么问题了。。。。
字体也配置好了

**Comment by levylll** [comment]
```
.vim/bundle/ale/after/plugin/ale.vim
```
在这个文件里

**Comment by TTWShell** [comment]
@levylll 我在三个系统都测试过，重新安装没有问题啊，无法重现你说的问题。或者你pull下最新的代码。执行下./install-plugins.sh update？

**Comment by levylll** [comment]
目前的commit 是 66529afea13efcc0ba5f332b8006730eb74c76dd这个
然后./install-plugins.sh update了，错误依然呀。。。。
我去ale那边发了个issue，看看有没有解决方案吧。。。。😢

**Comment by levylll** [comment]
看到了有人跟我一样的问题，能不能麻烦你先出个补丁，把这个变量给强行赋值一下呢？
我刚刚试了试在.vimrc里面直接赋值，用source就报错，你看那个人的临时处理方法怎么样合适？
[issue](https://github.com/w0rp/ale/issues/426#issuecomment-290183045)

**Comment by TTWShell** [comment]
@levylll  你好，我这边无法重现你的问题。等ale的作者解决吧。

**Comment by levylll** [comment]
@TTWShell OK了，那边有人把那个bug fix了，我这边重新装一下就没有问题了~开心

**Comment by TTWShell** [comment]
@levylll 👌
