### ISSUE TITLE
怎么去掉按tab后的小箭头，怎么copy整个文件内容

### ISSUE THREAD

**Issue by levylll** [TTWShell/legolas-vim#70]
冒昧又打扰，想请教一下，怎么去掉那个按tab的小箭头，因为要copy，小箭头就没法copy了。
```
>--->--->--->--->---if word not in entity_words_list:
>--->--->--->--->--->---entity_words_list.append(word)
```
另外想把文件内容整个copy到服务器，因为不能通过scp等，所以可能需要人工复制粘贴，有没有好的方法呢？
多谢了~

**Comment by TTWShell** [comment]
:retab

**Comment by levylll** [comment]
@TTWShell 小哥，你这个箭头真的是头疼。。。。怎么能彻底搞掉啊。。。。我发现我执行python都报失败。。。。

**Comment by TTWShell** [comment]
1. 箭头不是真的有箭头，只是把tab显示为箭头，为的是**查错方便**，这样一眼就能看到有tab，而不是等到执行程序时候发现报错。在py里面，本就应该使用4空格缩进，而不能用tab，请看pep8。
2. 把tab一键替换为4空格的方法之前也说过了，`:retab`。
3. 文件本身有tab、使用paste模式复制了代码、在paste模式使用整体缩进快捷键才会引入tab。

结论：把tab去掉只用执行命令`:retab`。

@levylll 以上

**Comment by levylll** [comment]
😢，我以前会默认把vim的的tab换成4个space
然后就是:retab不管事儿呀。。。。如下。。。箭头还是在。。。
不好意思呀
```
 92 >--->---
 93 >--->---
 94
 95
 NORMAL  PASTE  ./draw_raw_data.py +                unix  utf-8  python   82%    94:1
:retab
```
@TTWShell

**Comment by levylll** [comment]
@TTWShell 诶，抱歉，可能是我用法有问题，刚刚的 ` :retab ` 又生效了，非常抱歉的打扰了你。

**Comment by TTWShell** [comment]
@levylll 不要停留在paste模式，复制黏贴完代码退出paste模式，看你的powerline感觉不对。

**Comment by levylll** [comment]
@TTWShell 这应该是粘贴上来之后，才变成小方块了，在vim里面看起来没大问题。嗯，这个paste模式的话，额，确实也是我用的不太好的一点，有时候想要有时候不想要。。。。。

**Comment by levylll** [comment]
请问
```
~  87 
+  97
_ 108 
```
请问，数字左边这些小符号是什么意思啊

**Comment by TTWShell** [comment]
git diff插件。

**Comment by levylll** [comment]
@TTWShell 如果没有git add git commit 的话，这种小标记能不能去掉，有时候想复制，会有小符号的影响。
