### ISSUE TITLE
请问怎么才能完全卸载掉您的配置？

### ISSUE THREAD

**Issue by qoqoh** [TTWShell/legolas-vim#85]
您好！
我用了你的vim配置，在ubuntu里面一键安装，因为用着不合适，现在想删除，我用了sudo apt-get remove vim，但是提示我：Package 'vim' is not installed, so not removed，请问怎么才能完全卸载掉？盼回复！谢谢。

**Comment by TTWShell** [comment]
vim在ubuntu里是编译安装的，理论上你不需要卸载vim，只需要把~/.vimrc 删掉即可。ls 看下home目录，相关的备份也删掉。

**Comment by qoqoh** [comment]
好的。谢谢您的回复。
