### ISSUE TITLE
代码文档实时预览怎么关闭？

### ISSUE THREAD

**Issue by MulticsYin** [TTWShell/legolas-vim#97]
你好，一直在使用你的配置，做的特别好，谢谢！  
我这里出了一个问题，原本开发环境Ubuntu16.04一直都是正常的，最近因为工作变动，只能使用Windows，无奈在win10下安装了Ubuntu16.04子系统，配置Vim后文档提示出问题，想请问一下怎么取消这个功能？需要注释哪个插件吗？

**Comment by TTWShell** [comment]
你好，请问你说的文档提示具体指什么？
文档语法错误提示：w0rp/ale
代码自动补全：Valloric/YouCompleteMe
高亮：
" Syntaxes
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'othree/html5.vim'
Plug 'vim-scripts/nginx.vim'
Plug 'fatih/vim-go'
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'hynek/vim-python-pep8-indent'
Plug 'elzr/vim-json'
Plug 'dyng/ctrlsf.vim'
Plug 'kylef/apiblueprint.vim'
Plug 'leafgarland/typescript-vim'
这些配置文件都有注释。
如果感觉注释不清晰，欢迎pr补全。

**Comment by MulticsYin** [comment]
YCM 代码提示选中函数后在下面会有选中函数的使用文档，想关闭函数使用文档的提示，谢谢！

**Comment by TTWShell** [comment]
这个建议看下ycm的文档：
If you don't want this window to ever show up, add set completeopt-=preview to your vimrc. Also make sure that the g:ycm_add_preview_to_completeopt option is set to 0.

**Comment by MulticsYin** [comment]
可以了，谢谢！
在`.vimrc`文件 YCM 插件配置处添加以下两行：
`set completeopt-=preview`
`let g:ycm_add_preview_to_completeopt = 0`

**Comment by chencang7** [comment]
请问，在spacevim 中关闭ycm的函数使用文档应该怎么做？

**Comment by TTWShell** [comment]
> 请问，在spacevim 中关闭ycm的函数使用文档应该怎么做？

你好，我没用过spacevim，大致应该都是一样的。

If you don't want this window to ever show up, add set completeopt-=preview to your vimrc. Also make sure that the g:ycm_add_preview_to_completeopt option is set to 0.
